# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2

updates:

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # 7.0.0, requires Rust 2024 which is not stabilized in 1.84.1
      - dependency-name: "versions"
        update-types: [ "version-update:semver-major" ]
    groups:
      all:
        patterns: [ "*" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      all:
        patterns: [ "*" ]
