[database]
# ROAST_DATABASE_POOL_SIZE
# Maximum number of connections to the database. Default is 10.
pool_size = 10

# ROAST_DATABASE_URL
# Database connection URL.
url = "postgres://roast:roast@localhost:5432/roast"

# ROAST_DATABASE_SSL_MODE
# SSL mode for the database connection. One of allow, prefer, require, verify-ca, verify-full. Default is "prefer".
ssl_mode = "prefer"

# ROAST_DATABASE_SSL_CA
# Path to the root certificate file for the database connection
#ssl_ca = "./local/config/roast/server-ca.pem"

# ROAST_DATABASE_SSL_CERT
# Path to the certificate file for the database connection
#ssl_cert = "./local/config/roast/client-cert.pem"

# ROAST_DATABASE_SSL_KEY
# Path to the private key file for the database connection
#ssl_key = "./local/config/roast/client-key.pem"

[export]
# ROAST_EXPORT_PATH
# Directory to export JSON files to
path = "public/api/jvm/"
