[database]
# Maximum number of connections to the database. Default is 10.
pool_size = 10
# Database connection URL.
url = "postgres://postgres:postgres@localhost:5432/meta"

[export]
# Directory to export JSON files to
path = "data/"
