[database]
# Maximum number of connections to the database. Default is 10.
pool_size = 10
# Database connection URL.
url = "postgres://postgres:postgres@localhost:5432/roast"
# SSL mode for the database connection. One of allow, prefer, require, verify-ca, verify-full. Default is "prefer".
ssl_mode = "prefer"
# Path to the root certificate file for the database connection
#ssl_ca = "./local/config/roast/server-ca.pem"
# Path to the certificate file for the database connection
#ssl_cert = "./local/config/roast/client-cert.pem"
# Path to the private key file for the database connection
#ssl_key = "./local/config/roast/client-key.pem"

[export]
# Directory to export JSON files to
path = "data/"
