[tools]
"cargo:cargo-deny" = "0.17"

[env]
_.file = ".env.local"

[tasks.test]
run = """
  cargo fmt --all -- --check
  cargo clippy --all-targets --all-features -- -D warnings
  cargo deny check
  cargo test --all
"""

[tasks."run:fetch"]
run = """
cargo run -- fetch
"""

[tasks."run:export:triple"]
run = """
cargo run -- export triple
"""
