[tools]
"cargo:cargo-deny" = "0.17"

[env]
_.file = ".env.local"

[tasks.build]
run = """
cargo build --all-features
"""

[tasks.ci]
depends = ["lint", "test", "check"]

[tasks.lint]
depends = ["build"]
run = """
  cargo fmt --all -- --check
  cargo clippy --all-targets --all-features -- -D warnings
"""

[tasks.test]
depends = ["build"]
run = """
  cargo test --all
"""

[tasks.check]
depends = ["build"]
run = """
  cargo deny check
"""

[tasks."run:fetch"]
run = """
cargo run -- fetch
"""

[tasks."run:export:triple"]
run = """
cargo run -- export triple
"""
