[tools]
"cargo:cargo-deny" = "0.17"

[env]
_.file = ".env.local"

[tasks.build]
run = '''
cargo build --all-features
'''

[tasks.ci]
depends = ["lint", "test", "check"]

[tasks.lint]
depends = ["build"]
run = '''
cargo fmt --all -- --check
cargo clippy --all-targets --all-features -- -D warnings
'''

[tasks.test]
depends = ["build"]
run = '''
cargo test --all
'''

[tasks.check]
depends = ["build"]
run = '''
cargo deny check
'''

[tasks."api:publish"]
run = '''
AWS_BUCKET_NAME=roast.roele.dev

aws --version
aws s3 rm --recursive s3://${AWS_BUCKET_NAME}/
aws s3 cp --recursive --exclude "*.DS_Store" ./public/api s3://${AWS_BUCKET_NAME}/
'''

[tasks."run:fetch"]
run = '''
cargo run -- fetch
'''

[tasks."run:export:release-type"]
run = '''
cargo run -- export release-type --pretty -o linux,macosx,windows -a aarch64,arm32,i686,x86_64
'''

[tasks."run:export:vendor"]
run = '''
cargo run -- export vendor --pretty -o linux,macosx,windows -a aarch64,arm32,i686,x86_64
'''

[tasks."db:dump"]
run = '''
if ! command -v pg_dump &> /dev/null; then
  echo "pg_dump not found, please install it (brew install libpq)"
  exit 1
fi

pg_dump \
--host=$ROAST_DB_HOST \
--port=$ROAST_DB_PORT \
--username=$ROAST_DB_USR \
--dbname=$ROAST_DB_NAME \
--format=plain | gzip > backup/"$(date -u +"%Y-%m-%dT%H.%M.%SZ")-roast.sql.gz"
'''

[tasks."db:restore"]
usage = '''
arg <file> "Backup .sql.gz file to restore"
complete "file" run="ls backup/*.sql.gz | sort -r"
'''
run = '''
if ! command -v psql &> /dev/null; then
  echo "psql not found, please install it (brew install libpq)"
  exit 1
fi

gunzip -c {{arg(name="file")}} | \
psql postgresql://$ROAST_DB_HOST:$ROAST_DB_PORT/$ROAST_DB_NAME \
--username=$ROAST_DB_USR \
--password
'''
