name: "Build and Test"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read
  pull-requests: write

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo build --all-features
          $PWD/target/debug/jmeta -v

  unit:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [build-ubuntu]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all-features -- -D warnings
      - run: cargo fmt --all -- --check
      - run: cargo test --all-features
      - run: cargo deny check
