name: "Update Meta Data"

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always
  JMETA_DATABASE_URL: ${{ secrets.JMETA_DATABASE_URL }}
  RUST_BACKTRACE: 1
  RUST_LOG: jmeta=INFO
  GH_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - uses: Swatinem/rust-cache@v2

      - name: Update Meta Data
        run: |
          cargo run -- fetch

      - name: Export Meta Data
        run: |
          cargo run -- export triple

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update metadata
          title: Update metadata
          base: main
          labels: automated-pr
          assignees: ${{ vars.CREATE_PR_ASSIGNEES || 'roele' }}
          reviewers: ${{ vars.CREATE_PR_REVIEWERS || 'roele' }}
          branch: issues/update-metadata
          delete-branch: true
