name: "Update Data"

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:
    inputs:
      vendors:
        description: 'Vendors to update (e.g. temurin zulu). No value means all vendors.'
        default: ''

permissions:
  contents: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always
  RAYON_NUM_THREADS: ${{ vars.RAYON_NUM_THREADS }}
  ROAST_DATABASE_URL: ${{ secrets.ROAST_DATABASE_URL }}
  RUST_BACKTRACE: 1
  RUST_LOG: roast=INFO
  GH_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "roast"

      - name: Update Data
        run: |
          cargo run -- fetch ${{ github.event.inputs.vendors }}

      - name: Export Data
        run: |
          cargo run -- export release-type --pretty -o linux,macosx,windows -a aarch64,arm32,i686,x86_64

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update data
          title: Update data
          base: main
          labels: automated-pr
          assignees: ${{ vars.CREATE_PR_ASSIGNEES || 'roele' }}
          reviewers: ${{ vars.CREATE_PR_REVIEWERS || 'roele' }}
          branch: issues/update-data
          delete-branch: true
